-- AlterTable
ALTER TABLE "AlertSettings" ADD COLUMN     "focStandaloneMin" DOUBLE PRECISION NOT NULL DEFAULT 100000,
ADD COLUMN     "netMinExcess" DOUBLE PRECISION NOT NULL DEFAULT 20000,
ADD COLUMN     "netOverPct" DOUBLE PRECISION NOT NULL DEFAULT 25;

-- AlterTable
ALTER TABLE "FocActual" ADD COLUMN     "category" TEXT;

